---
- hosts: all
  become: true

  tasks:
  - name: Create directory
    file:
      path: "/home/diegosoda/oracle" 
      state: directory
      mode: 0755        

  - name: Download openjdk
    unarchive:
      src: "https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz"
      dest: "/home/diegosoda/oracle"
      remote_src: yes

  - name: Install Java
    dnf:
      name: java-20.0.1-openjdk
      state: present

  - name: Create directory
    file:
      path: "/home/diegosoda/tomcat8"
      state: directory
      mode: 0755

  - name: Download and install tomcat
    unarchive:
      src: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.89/bin/apache-tomcat-8.5.89.tar.gz"
      dest: "/home/diegosoda/tomcat8"
      remote_src: yes
      mode: 0755

  - name: Start the tomcat instance
    shell:
      "./startup.sh"
    args:
      chdir: "/home/diegosoda/tomcat8/apache-tomcat-8.5.89/bin"
