---
- hosts: all
  become: true
  tasks:
   - name: Install Apache and MariaDB
     dnf:
       name: 
         - httpd
         - mariadb-server  
       state: latest

   - name: Start httpd service
     service:
       name: httpd  
       state: started

   - name: Start MariaDB service
     service:
       name: mariadb
       state: started       
