---
- hosts: all
  become: true
  vars:
    repo_url: https://download.docker.com/linux/centos/docker-ce.repo
    repo_key: https://download.docker.com/linux/centos/gpg

  tasks:
   - name: Install required packages
     yum:
       name: "{{ packages }}"
       state: present
     vars:
       packages:
         - yum-utils
         - device-mapper-persistent-data
         - lvm2
         - epel-release

   - name: Add officiel docker GPG key
     rpm_key:
       key: "{{repo_key}}"
       state: present

   - name: Add docker repo
     get_url:
       url: "{{repo_url}}"
       dest: /etc/yum.repos.d/docer-ce.repo

   - name: Install docker CE
     dnf:
       name: docker-ce
       state: latest

   - name: Enable and start docker service
     systemd:
       name: docker
       state: started
       enabled: yes

   - name: Install docker-compose
     command: >
       curl -l "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" 
       -o /usr/local/bin/docker-compose
     args:
       creates: /usr/local/bin/docker-compose

   - name: Set execute permissions for Docker Compose
     file:
       path: /usr/local/bin/docker-compose
       mode: 'u+x'

          
