---
- hosts: all
  become: true

  tasks:
  - name: Create a directory
    file:
      path: "/opt/oracle"
      mode: 0755 
      state: directory        

  - name: Download openjdk
    unarchive:
      src: "https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz"
      dest: "/opt/oracle"
      remote_src: yes

  - name: Install Java
    dnf:
      name: java-17-openjdk-devel
      state: present

  - name: Create a directory
    file:
      path: "/opt/tomcat"
      owner: diegosoda
      group: diegosoda
      mode: 0755
      state: directory

  - name: Download and install tomcat
    unarchive:
      src: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz"
      dest: "/opt/tomcat"
      remote_src: yes
      mode: 0755

  - name: Start the tomcat instance
    shell:
      "./startup.sh"
    args:  
      chdir: "/opt/tomcat/apache-tomcat-9.0.75/bin"
