---
- hosts: all
  become: true
  vars:
    repo_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    repo_key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

  tasks:
   - name: Add Jenkins repository
     get_url:
       url: "{{repo_url}}"
       dest: /etc/yum.repos.d/jenkins.repo

   - name: Import jenkins key from url
     rpm_key:
       state: present
       key: "{{repo_key}}"

   - name: Upgrade all packages
     dnf:
       name: "*"
       state: latest        

   - name: Install Java
     dnf:
       name: java-11-openjdk
       state: present

   - name: Install Jenkins
     dnf:
       name: jenkins
       state: latest

   - name: Start Jenkins
     systemd:
       daemon-reload: yes     
       name: jenkins
       state: started

   - name: Wait for Jenkins to be accessible
     uri:
       url: http://localhost:8080/
     register: jenkins_response
     until: "jenkins_response.status == 200"
     retries: 10
     delay: 10

   - name: Display initial Jenkins password
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     register: jenkins_password
     changed_when: false

   - name: Display initial Jenkins password
     debug:
       var: jenkins_password.stdout_lines  

