---
- hosts: all
  become: true
  vars:
    repo_url: https://pkg.jenkins.io/redhat/jenkins.repo
    repo_key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

  tasks:
   - name: Add Jenkins repository
     yum_repository:
       name: jenkins
       description: Jenkins Repository
       baseurl: "{{repo_url}}"
       gpgcheck: true
       gpgkey: "{{repo_key}}"
       enabled: true

   - name: Install Java
     dnf:
       name: java-11-openjdk
       update_cache: yes
       state: present

   - name: Install Jenkins
     dnf:
       name: jenkins
       state: present

   - name: Start Jenkins service
     service:
       name: jenkins
       state: started
       enabled: true

   - name: Wait for Jenkins to be accessible
     uri:
       url: http://locolhost:195
     register: jenkins_response
     until: "jenkins_response.status == 200"
     retries: 10
     delay: 10

   - name: Display initial Jenkins password
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     register: jenkins_password
     changed_when: false

   - name: Display initial Jenkins password
     debug:
       var: jenkins_password.stdout_lines  

