---
- hosts: all
  become: true

  tasks:
  - name: Add adoptopenjdk repository
    get_url:
      url: "https://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/8/adoptopenjdk.repo"
      dest: "/etc/yum.repos.d/adoptopenjdk.repo"

  - name: Install OpenJDK
    package:
      name: adoptopenjdk-11-hotspot
      state: latest

  - name: Create a direcory
    file:
      path: "/home/diegosoda/tomcat8"
      state: directory
      mode: 0755

  - name: Download and install tomcat
    unarchive:
      src: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.89/bin/apache-tomcat-8.5.89.tar.gz"
      dest: "/home/diegosoda/tomcat8"
      remote_src: yes
      mode: 0755

  - name: Start the tomcat instance
    shell:
      "./startup.sh"
    args:
      chdir: "/home/diegosoda/tomcat8/apache-tomcat-8.5.89/bin"
